redis:
  host: db.darixsmp.es
  port: 6379
  password: ""
  cluster: "SURVIVAL_DarixTeleport"
mongo:
  uri: "mongodb://db.darixsmp.es:27017"
  database: "SURVIVAL_DarixTeleport"

server: "SURVIVAL-S-01"

timeouts: # In milliseconds
  get-teleport-location-request: 3000 # 3 seconds
  pending-teleport-ttl: 10000 # 10 seconds
  user-quit: 600000 # 10 minutes

home-limits: # darixteleport.homes.<rank>
  default: 1
  vip: 3
  mvp: 5
  ultra: 10

countdown:
  duration: 3 # In seconds
  max-movement: 0.5 # In blocks